### ISSUE TITLE
[관리자] View Endpoint Test 정의

### ISSUE THREAD

**Issue by y2gon2** [y2gon2/fastcampus-project-board-admin#11]
관리자 서비스에 제공할 예정인 view 와 각 specification 을 test 로 미리 정의한 이후,
필요한 기능을 구현하면서 상세 사항을 issue 로 정리한다. 

## TODO
 * [x] Main view
 * [x] 게시글 관리 view
 * [x] 댓글 관리 view
 * [x] 회원 관리 view
 * [x] Admin 회원 view

**Comment by y2gon2** [comment]
기존 test 실패 상태에서 view templates 구현 및 단순 get mapping controller method 를 추가하여 test 를 통과하는 상태로 추가 작업하여 반영함.
