### ISSUE TITLE
[관리자] 로그인 페이지 기능 Test 정의

### ISSUE THREAD

**Issue by y2gon2** [y2gon2/fastcampus-project-board-admin#24]
로그인 기능을 구현하기 위해  Test 가 필요한지 검토하고, 관리자 회원 기능과 카카오 OAuth 인증을 준비한다.

## TODO

* [x] 로그인 설정 및 test 검토
* [x] 관리자 회원 기능 검토
* [x] 카카오 OAuth 인증 준비 및 Test 검토
